version: "3.7"

services:
   frontend:
      build:
         context: .
         dockerfile: ./frontend/Dockerfile-ssl
      ports:
         - 80:3000
      volumes:
         - ./frontend/my-public-assets:/app/public/my-assets
      restart: unless-stopped
   backend:
      build:
         context: ./backend
      ports:
         - 5001:5001
      restart: unless-stopped
