version: "3.7"

services:
   yap-frontend:
      build:
         context: ./frontend
      ports:
         - 4000:3000
      restart: unless-stopped
   yap-backend:
      build:
         context: ./backend
      ports:
         - 5001:5001
      restart: unless-stopped
